language: python
dist: xenial

python:
  - "3.6"

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - SOURCE_PATH=$TRAVIS_BUILD_DIR/docs/source
    - API_PATH=$SOURCE_PATH/api
    - BUILD_PATH=$TRAVIS_BUILD_DIR/docs/build
    - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html

cache: 
 - directories:
   - $DOWNLOADS
   - $HOME/.cache/pip

before_install:
  # install neurodebian (without spyware)
  - sudo apt-get update -qq
  - source /etc/lsb-release
  - wget -O- http://neuro.debian.net/lists/${DISTRIB_CODENAME}.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add -;
  - sudo apt-get update -qq

  # necessary for nipype plots
  - sudo apt-get install -y -qq graphviz

  # get the correct files
  - python make.py --get_files

install:
  # install requirements
  - pip install -e git+https://github.com/wonambi-python/wonambi.git#egg=wonambi
  - pip install pytest pytest-cov codecov
  - pip install -e .

script:
  - py.test --cov=boavus tests
  - find tests/data -type f -printf "\n%TY/%Tm/%Td %TH:%TM:%TS\t%s\n" -exec md5sum \{\} \;

after_success:
  - codecov
  - pip install sphinx sphinx_rtd_theme
  - sphinx-apidoc -fMeT -o $API_PATH boavus
  - sphinx-build -T -b html -d $BUILD_PATH/doctrees $SOURCE_PATH $HTML_PATH

notifications:
  email: false

deploy:
 - provider: pages
   skip_cleanup: true
   target_branch : gh-pages
   local_dir : docs/build/html
   repo : gpiantoni/boavus
   github_token : $GITHUB_TOKEN
