language: python

dist: xenial

python:
  - "3.6"

services:
  - docker

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - DERIVATIVES=tests/data/derivatives
    - INSTALL=$HOME/bin
    - SOURCE_PATH=$TRAVIS_BUILD_DIR/docs/source
    - API_PATH=$SOURCE_PATH/api
    - BUILD_PATH=$TRAVIS_BUILD_DIR/docs/build
    - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html

cache: 
  directories:   
    - $DOWNLOADS
    - $TRAVIS_BUILD_DIR/.cache/pip

before_install:
  - ./make.py --get_files

  - pip install neurodocker
  - neurodocker generate docker 
    --base=neurodebian:buster-non-free --pkg-manager=apt 
    --install apt-utils git ssh python3-pip gcc python3-setuptools python3-dev python3-wheel 
    fsl file 
    graphviz 
    --add-to-entrypoint='source /etc/fsl/fsl.sh' 
    --add-to-entrypoint='pip3 install --user -e .[test]' 
    --user neuro 
    --env USER=neuro 
    --env PATH='${PATH}:${HOME}/.local/bin:${HOME}/docker' 
    > dockerfile

  # use the same user UID for travis / docker
  - sed -i "s/RUN useradd/& -u $UID/" dockerfile

  - cat dockerfile

install:
  - docker build --tag gpiantoni/boavus .

script:
  - docker run -i -t --rm 
    -v $TRAVIS_BUILD_DIR:/home/neuro 
    -w /home/neuro 
    --user neuro 
    gpiantoni/boavus 
    python3 make.py --tests

after_success:
  - ls tests/data/analysis/fmri -l
  - pip install sphinx sphinx_rtd_theme codecov
  - codecov

notifications:
  email: false

deploy:
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    on:
      tags: true
  - provider: script
    script: bash docker/docker_push
