language: python

dist: xenial

python:
  - "3.6"

services:
  - docker

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - DERIVATIVES=tests/data/derivatives
    - INSTALL=$HOME/bin
    - SOURCE_PATH=$TRAVIS_BUILD_DIR/docs/source
    - API_PATH=$SOURCE_PATH/api
    - BUILD_PATH=$TRAVIS_BUILD_DIR/docs/build
    - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html


before_install:
  - pip install neurodocker
  - neurodocker generate docker 
    --base=neurodebian:buster-non-free --pkg-manager=apt 
    --install apt-utils git ssh python3-pip gcc python3-setuptools python3-dev python3-wheel 
    fsl file 
    graphviz 
    --add-to-entrypoint='source /etc/fsl/fsl.sh' 
    --user neuro 
    --env USER=neuro 
    --env PATH='${PATH}:/home/neuro/.local/bin:/home/neuro/bin' 
    > dockerfile
  - cat dockerfile

install:
  - docker build --tag basic .

script:
  - docker run -i -t --rm 
    --name running 
    --user neuro 
    -v /home/gio/tools/boavus:/home/neuro 
    -w /home/neuro 
    basic 
    bash docker_tests.sh

after_success:
  - pip install sphinx sphinx_rtd_theme

notifications:
  email: false
