language: python

dist: xenial

python:
  - "3.6"

services:
  - docker

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - DERIVATIVES=tests/data/derivatives
    - INSTALL=$HOME/bin
    - SOURCE_PATH=$TRAVIS_BUILD_DIR/docs/source
    - API_PATH=$SOURCE_PATH/api
    - BUILD_PATH=$TRAVIS_BUILD_DIR/docs/build
    - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html


before_install:
  - chmod o+rwx .
  - pip install neurodocker
  - neurodocker generate docker 
    --base=neurodebian:buster-non-free --pkg-manager=apt 
    --install apt-utils git ssh python3-pip gcc python3-setuptools python3-dev python3-wheel
    fsl
    --add-to-entrypoint='source /etc/fsl/fsl.sh' 
    --user neuro --env USER=neuro 
    > dockerfile
  - cat dockerfile
  - docker build --tag basic .

install:
  - docker run -i -t -d 
    --name running 
    --user neuro
    -v /home/travis/build/gpiantoni/boavus:/home/neuro
    -w /home/neuro
    basic 

script:
  - docker exec running pwd
  - docker exec running bash -c "python3 -V"
  - docker exec running pip3 install --user -e .
  - docker exec running bash -c "fsl5.0-flirt -version"

after_success:
  - docker exec running pip install sphinx sphinx_rtd_theme

notifications:
  email: false
