language: python
dist: xenial

python:
  - "3.6"

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - SOURCE_PATH=$TRAVIS_BUILD_DIR/docs/source
    - API_PATH=$SOURCE_PATH/api
    - BUILD_PATH=$TRAVIS_BUILD_DIR/docs/build
    - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html
    # stand-in functions without installing the whole package
    - PATH=$PATH:bin 

cache: 
 - directories:
   - $DOWNLOADS
   - $HOME/.cache/pip

before_install:
  - sudo apt-get update -qq
  - wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py
  - python2 fslinstaller.py -l
  - mkdir fsl
  - python2 fslinstaller.py -d fsl -V 6.0.0
  - export FSLOUTPUTTYPE=NIFTI_GZ

  # necessary for nipype plots
  - sudo apt-get install -y -qq graphviz

  # get the correct files
  - python make.py --get_files

install:
  # install requirements
  - pip install -e git+https://github.com/wonambi-python/wonambi.git#egg=wonambi
  - pip install pytest pytest-cov codecov
  - pip install -e .

script:
  - bin/recon-all
  - recon-all
  - travis_wait python make.py --tests

after_success:
  - codecov
  - pip install sphinx sphinx_rtd_theme
  - sphinx-apidoc -fMeT -o $API_PATH boavus
  - sphinx-build -T -b html -d $BUILD_PATH/doctrees $SOURCE_PATH $HTML_PATH

notifications:
  email: false

deploy:
 - provider: pages
   skip_cleanup: true
   target_branch : gh-pages
   local_dir : docs/build/html
   repo : gpiantoni/boavus
   github_token : $GITHUB_TOKEN
