language: python
dist: xenial

python:
  - "3.6"

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - SOURCE_PATH=$TRAVIS_BUILD_DIR/docs/source
    - API_PATH=$SOURCE_PATH/api
    - BUILD_PATH=$TRAVIS_BUILD_DIR/docs/build
    - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html

cache: 
 - directories:
   - $DOWNLOADS
   - $HOME/.cache/pip

before_install:
  # install neurodebian (without spyware)
  - sudo apt-get update -qq
  - source /etc/lsb-release
  - wget -O- http://neuro.debian.net/lists/${DISTRIB_CODENAME}.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add -;
  - sudo apt-get update -qq

  # install fsl
  - sudo apt-get install -y -qq fsl-core
  - source /etc/fsl/fsl.sh
  - export FSLOUTPUTTYPE=NIFTI_GZ

  # necessary for nipype plots
  - sudo apt-get install -y -qq graphviz

  # install freesurfer
  - wget -q --directory-prefix=$DOWNLOADS https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.1/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1.tar.gz ;
  - mkdir $LIB -p
  - tar 
    -xf $DOWNLOADS/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1.tar.gz 
    -C $LIB 
    --exclude='freesurfer/trctrain' 
    --exclude='freesurfer/subjects/fsaverage_sym' 
    --exclude='freesurfer/subjects/fsaverage3' 
    --exclude='freesurfer/subjects/fsaverage4'
    --exclude='freesurfer/subjects/fsaverage5' 
    --exclude='freesurfer/subjects/fsaverage6' 
    --exclude='freesurfer/subjects/cvs_avg35' 
    --exclude='freesurfer/subjects/cvs_avg35_inMNI152' 
    --exclude='freesurfer/subjects/V1_average' 
    --exclude='freesurfer/average/mult-comp-cor' 
    --exclude='freesurfer/lib/cuda' 
    --exclude='freesurfer/lib/qt' 
    --exclude='freesurfer/lib/tcltktixblt'
    --exclude='freesurfer/lib/vtk' 
    --exclude='freesurfer/diffusion' 
    freesurfer ;
  - echo -e $FREESURFER_LICENSE > $LIB/freesurfer/license.txt
  - export FREESURFER_HOME=$LIB/freesurfer
  - source $FREESURFER_HOME/SetUpFreeSurfer.sh

  # get the correct files
  - python make.py --get_files

install:
  # install requirements
  - pip install -e git+https://github.com/wonambi-python/wonambi.git#egg=wonambi
  - pip install pytest pytest-cov codecov
  - pip install -e .

script:
  - py.test --cov=boavus --disable-warnings tests

after_success:
  - codecov
  - pip install sphinx sphinx_rtd_theme
  - sphinx-apidoc -fMeT -o $API_PATH boavus
  - sphinx-build -T -b html -d $BUILD_PATH/doctrees $SOURCE_PATH $HTML_PATH

notifications:
  email: false

deploy:
 - provider: pages
   skip_cleanup: true
   target_branch : gh-pages
   local_dir : docs/build/html
   repo : gpiantoni/boavus
   github_token : $GITHUB_TOKEN
