language: python

python:
 - "3.6"

env:
  global:
   - DOWNLOADS=$HOME/downloads
   - CACHE=$HOME/cache
   - DERIVATIVES=tests/data/derivatives

cache: 
 - directories:
   - $CACHE
   - $HOME/.cache/pip

before_install:
 - mkdir $DERIVATIVES/freesurfer -p
 - if [ ! -d $CACHE/freesurfer ]; then
    wget -q --directory-prefix=$DOWNLOADS ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz ;
    tar -C $CACHE -xf $DOWNLOADS/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz freesurfer/subjects/bert ;
   fi
 - cp $CACHE/freesurfer/subjects/bert $DERIVATIVES/freesurfer/bert -r

install: 
 # install requirements
 - pip install nibabel 
 - pip install pytest pytest-cov codecov
 - pip install -e .

script:
    - py.test --cov=bidso tests

after_success:
 - codecov

notifications:
 email: false

deploy:
 - provider: pypi
   user: $PYPI_USER
   password: $PYPI_PASSWORD
   on:
     tags: true
