language: python

python:
  - "3.6"

env:
  global:
    - DOWNLOADS=$HOME/downloads
    - LIB=$HOME/lib
    - DERIVATIVES=tests/data/derivatives
    - INSTALL=$HOME/bin

cache: 
 - directories:
   - $HOME/.cache/pip

before_install:
  - sudo apt-get update -qq

  # install fsl
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get -y update && sudo apt-get install -y -qq fsl-core
  - source /etc/fsl/fsl.sh
  - export FSLOUTPUTTYPE=NIFTI_GZ

  # install freesurfer
  - mkdir $DERIVATIVES/freesurfer -p
  - wget -q --directory-prefix=$DOWNLOADS https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.1/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1.tar.gz ;
  - mkdir $LIB -p
  - tar 
    -xf $DOWNLOADS/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1.tar.gz 
    -C $LIB 
    --exclude='freesurfer/trctrain' 
    --exclude='freesurfer/subjects/fsaverage_sym' 
    --exclude='freesurfer/subjects/fsaverage3' 
    --exclude='freesurfer/subjects/fsaverage4'
    --exclude='freesurfer/subjects/fsaverage5' 
    --exclude='freesurfer/subjects/fsaverage6' 
    --exclude='freesurfer/subjects/cvs_avg35' 
    --exclude='freesurfer/subjects/cvs_avg35_inMNI152' 
    --exclude='freesurfer/subjects/V1_average' 
    --exclude='freesurfer/average/mult-comp-cor' 
    --exclude='freesurfer/lib/cuda' 
    --exclude='freesurfer/lib/qt' 
    --exclude='freesurfer/lib/tcltktixblt'
    --exclude='freesurfer/lib/vtk' 
    --exclude='freesurfer/diffusion' 
    freesurfer ;
  - echo -e FREESURFER_LICENSE > $LIB/freesurfer/license.txt
  - export FREESURFER_HOME=$LIB/freesurfer
  - source $FREESURFER_HOME/SetUpFreeSurfer.sh
  - ln -s $LIB/freesurfer/subjects/bert $DERIVATIVES/freesurfer/sub-bert -r

  # geckodriver
  - json=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest)
  - url=$(echo "$json" | jq -r '.assets[].browser_download_url | select(contains("linux64"))')
  - curl -s -L "$url" | tar -xz
  - chmod +x geckodriver
  - mkdir $INSTALL -p
  - mv geckodriver $INSTALL
  - export PATH=$INSTALL:$PATH

install:

  # install requirements
  - pip install numpy scipy
  - pip install pyqt5==5.9.2  # opengl doesn't work with 5.10
  - pip install nibabel vispy
  - pip install -e git+https://github.com/wonambi-python/wonambi.git@bids#egg=wonambi
  - pip install -e git+https://github.com/gpiantoni/bidso.git#egg=bidso  # this should be in pypi
  - pip install plotly
  - pip install -e git+https://github.com/gpiantoni/exportimages.git#egg=exportimages  # this should be in pypi
  - pip install pytest pytest-qt pytest-cov codecov pytest-travis-fold
  - pip install -e .

before_script:
  - export DISPLAY=:99.0;
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;

script:
  - python -c "import vispy; print(vispy.sys_info())"
  - py.test --cov=boavus tests
  - ls tests/data/* -lR
  - cat tests/parameters/*

after_success:
  - codecov

notifications:
  email: false
