language: python

python:
 - "3.6"

env:
  global:
   - DOWNLOADS=$HOME/downloads
   - CACHE=$HOME/cache
   - DERIVATIVES=tests/data/derivatives

cache: 
 - directories:
   - $CACHE
   - $HOME/.cache/pip

before_install:
 - sudo apt-get update
 - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
 - sudo apt-get -y update && sudo apt-get install -y -qq fsl-core
 - source /etc/fsl/fsl.sh
 - export FSLOUTPUTTYPE=NIFTI_GZ
 - mkdir $DERIVATIVES/freesurfer -p
 - if [ ! -d $CACHE/freesurfer ]; then
    wget -q --directory-prefix=$DOWNLOADS ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz ;
    tar -C $CACHE 
    --exclude='freesurfer/trctrain' 
    --exclude='freesurfer/subjects/fsaverage_sym' 
    --exclude='freesurfer/subjects/fsaverage3' 
    --exclude='freesurfer/subjects/fsaverage4'
    --exclude='freesurfer/subjects/fsaverage5' 
    --exclude='freesurfer/subjects/fsaverage6' 
    --exclude='freesurfer/subjects/cvs_avg35' 
    --exclude='freesurfer/subjects/cvs_avg35_inMNI152' 
    --exclude='freesurfer/subjects/V1_average' 
    --exclude='freesurfer/average/mult-comp-cor' 
    --exclude='freesurfer/lib/cuda' 
    --exclude='freesurfer/lib/qt' 
    -xvf $DOWNLOADS/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz 
    freesurfer  ;
   fi
 - echo -e FREESURFER_LICENSE > $CACHE/freesurfer/license.txt
 - export FREESURFER_HOME=$CACHE/freesurfer
 - source $FREESURFER_HOME/SetUpFreeSurfer.sh
 - ln -s $CACHE/freesurfer/subjects/bert $DERIVATIVES/freesurfer/bert -r

install: 
 # install requirements
 - pip install nibabel  wonambi
 - pip install -e git+https://github.com/gpiantoni/bidso.git#egg=bidso  # this should be in pypi
 - pip install pytest pytest-cov codecov
 - pip install -e .

script:
    - py.test --cov=boavus tests

after_success:
 - ls tests/data/* -lR
 - codecov

notifications:
 email: false
